Front end: added "positions qualified to give interview" to profile page
googleinterns/InterviewMe pull request #123
Opened 2020-07-24 15:12 UTC by apluscs

lf this gets approved l'll add the other 7 jobs and copy to the registration form.
![Screenshot 2020-07-24 at 11 10 20 AM](https://user-images.githubusercontent.com/34817835/88406239-64546200-cd9e-11ea-886f-c04cab83ffc5.png)
![Screenshot 2020-07-24 at 11 10 29 AM](https://user-images.githubusercontent.com/34817835/88406241-64ecf880-cd9e-11ea-892f-ff82d40c15ac.png)

2020-07-24 17:52 UTC, GrantComm approved these changes
LGTM

2020-07-24 17:54 UTC, meagancheese requested changes
Please put the buttons in container divs and center them.

2020-07-27 14:32 UTC, meagancheese approved these changes
LGTM

2020-07-27 20:08 UTC, acmcarther approved these changes

2020-07-28 13:00 UTC, merged