Added getInRange() to ScheduledInterviewDao
googleinterns/InterviewMe pull request #138
Opened 2020-07-29 23:37 UTC by apluscs

Purpose: to get all Scheduled Interviews for a shadow to choose from, later we can tweak the method to filter by a specific job
Side note: Everything related to Shadow will go into the shadow branch, so master doesn't get messed up in prep for the demo

Side note: lt's bugging me how we set up this Dao's time filtering to go from (startTime of earliest, endTime of latest). lt should be (startTime of earliest, startTime of latest). l was surprised when l realized this wasn't the case, and there's all this "add 60, subtract 60" mental work that should be cut out. l can do that in this PR if everyone is onboard with this change.

2020-07-30 15:17 UTC, GrantComm approved these changes

2020-07-30 16:16 UTC, meagancheese requested changes
Mostly comment changes, and then making sure to sort in Fake Dao

2020-07-30 16:16 UTC, meagancheese commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +   * Returns a list of all scheduled ScheduledInterview objects whose startTime is between minTime
No need to say scheduled ScheduledInterview. minTime and maxTime are not in milliseconds, and just say 'objects between...', don't bring startTime into it.

2020-07-30 16:16 UTC, meagancheese commented on src/main/java/com/google/sps/data/FakeScheduledInterviewDao.java
> +   * and maxTime. minTime and maxTime are in milliseconds.
Fix this comment similarly to the other one.

2020-07-30 16:16 UTC, meagancheese commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +   * Returns a list of all scheduled ScheduledInterview objects whose startTime is between minTime
Are they sorted?

2020-07-30 16:16 UTC, meagancheese commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +   * Returns a list of all scheduled ScheduledInterview objects whose startTime is between minTime
I think they are, say as much.

2020-07-30 16:16 UTC, meagancheese commented on src/main/java/com/google/sps/data/FakeScheduledInterviewDao.java
> +   * and maxTime. minTime and maxTime are in milliseconds.
Also, be sure to sort here.

2020-07-30 16:16 UTC, meagancheese commented on src/main/java/com/google/sps/data/ScheduledInterviewDao.java
> +  // minTime to maxTime. minTime and maxTime are in milliseconds.
minTime and maxTime are not in milliseconds, they're Instants.

2020-07-30 16:16 UTC, meagancheese commented on src/main/java/com/google/sps/data/ScheduledInterviewDao.java
> +  // minTime to maxTime of a user. minTime and maxTime are in milliseconds.
minTime and maxTime are not in milliseconds.

2020-07-31 18:40 UTC, meagancheese approved these changes
A handful of nits, otherwise LGTM.

2020-07-31 18:40 UTC, meagancheese commented on src/main/java/com/google/sps/data/ScheduledInterviewDao.java
> +  // Returns a list, sorted by start time, of all scheduled ScheduledInterview objects ranging from
Nit: Remove the word "scheduled"

2020-07-31 18:40 UTC, meagancheese commented on src/main/java/com/google/sps/data/ScheduledInterviewDao.java
> +  // Returns a list of all scheduled ScheduledInterview objects ranging from minTime to maxTime of a
Nit: remove the word "scheduled"

2020-07-31 18:40 UTC, meagancheese commented on src/test/java/com/google/sps/data/DatastoreScheduledInterviewTest.java
> +  public void getsScheduledInterviewInRange() {
Nit: Interviews (plural)

2020-07-31 18:40 UTC, meagancheese commented on src/test/java/com/google/sps/data/DatastoreScheduledInterviewTest.java
> +  public void getsScheduledInterviewInRangeEmpty() {
Nit: again, plural

2020-07-31 19:09 UTC, jalexanderqed approved these changes

2020-07-31 19:29 UTC, merged