WIP: logout out of site,  not all of Google
googleinterns/InterviewMe pull request #160
Opened 2020-08-04 17:30 UTC by apluscs

How to test deployment without messing up deployed site?

2020-08-04 20:51 UTC, meagancheese requested changes
Some changes needed for what's happening when user is logged in vs. logged out.

2020-08-04 20:51 UTC, meagancheese commented on src/main/webapp/about.js
> +      document.getElementById('login-tab').href = status.loginUrl;
Shouldn't this be logout-tab?

2020-08-04 20:51 UTC, meagancheese commented on src/main/webapp/about.js
> +      document.getElementById('login-tab').removeAttribute('hidden');
You still need to set the link on the login-tab.

2020-08-04 20:51 UTC, meagancheese commented on src/main/webapp/authentication.js
> +      console.log('redirected ' + response.url);
Remove

2020-08-04 20:51 UTC, meagancheese commented on src/main/webapp/script.js
> +      document.getElementById('login-tab').href = status.loginUrl;
This should be logout-tab

2020-08-04 20:51 UTC, meagancheese commented on src/main/webapp/script.js
> +      document.getElementById('login-tab').removeAttribute('hidden');
Set this link

2020-08-05 14:38 UTC, meagancheese approved these changes

2020-08-05 14:51 UTC, GrantComm approved these changes

2020-08-05 17:12 UTC, acmcarther approved these changes

2020-08-05 17:35 UTC, merged