Adds DatastoreScheduledInterviewDAO
googleinterns/InterviewMe pull request #60
Opened 2020-07-08 14:08 UTC by GrantComm

2020-07-08 14:50 UTC, meagancheese requested changes
Some notes and questions

2020-07-08 14:50 UTC, meagancheese commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +  // @param datastore the DatastoreService we're using to interact with Datastore.
Capitalize The

2020-07-08 14:50 UTC, meagancheese commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +    } catch (Exception e) {
I think this needs to be a more specific exception, not sure where we're at on this.

2020-07-08 14:50 UTC, meagancheese commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +    CompositeFilter compositeFilter = CompositeFilterOperator.and(interviewerFilter, intervieweeFilter);
Does this and function act as an "OR" operator? Meaning will it catch both cases where the Person is an interviewer and an interviewee and not only look for situations where both the interviewer and the interviewee are the Person?

2020-07-08 14:50 UTC, meagancheese commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +  }
Does this really update? It's not deleting the previous configuration from datastore as far as I can tell.

2020-07-08 14:50 UTC, meagancheese commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +   */
Be consistent with these one line javadocs (either /** text  */ OR
/**
text
*/)

2020-07-08 15:01 UTC, apluscs requested changes
Small changes

2020-07-08 15:01 UTC, apluscs commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +   * and return them as a list of scheduledInterview objects.
Nit: returns not return

2020-07-08 15:01 UTC, apluscs commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +
Nit: rm extra line

2020-07-08 15:01 UTC, apluscs commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +  public Entity create(ScheduledInterview scheduledInterview) {
change function name to scheduledInterviewToEntity for clarity

2020-07-08 15:01 UTC, apluscs commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +    } catch (Exception e) {
Make Exception specific: `com.google.appengine.api.datastore.EntityNotFoundException e`
General Exceptions are a no-no

2020-07-08 15:01 UTC, apluscs commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +    Key key = KeyFactory.createKey("id", id);
"id" is the kind. Should be "ScheduledInterview"

2020-07-08 15:01 UTC, apluscs commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +   * and return it as a scheduledInterview object.
Nit: scheduledInterview should be ScheduledInterview because it's the class

2020-07-08 15:01 UTC, apluscs commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +    CompositeFilter compositeFilter = CompositeFilterOperator.and(interviewerFilter, intervieweeFilter);
This means you're searching for someone who is the interview AND interviewee. Should be composite or.

2020-07-08 16:56 UTC, acmcarther commented
Just passing through, quick question.

It looks like the commits for this branch start at an unusual point. Was this branch really created 12 days ago? I suspect you had a pretty stale master branch when you created this branch but I'm not sure.

2020-07-09 19:05 UTC, acmcarther commented on src/main/java/com/google/sps/data/DatastoreScheduledInterviewDao.java
> +  public Optional<ScheduledInterview> get(long id) {
Remember to include `@Override` where applicable.

2020-07-09 19:05 UTC, acmcarther approved these changes
LGTM % one change.

2020-07-09 19:23 UTC, meagancheese approved these changes
LGTM

2020-07-10 14:15 UTC, apluscs approved these changes

2020-07-10 14:17 UTC, merged