Modified interface to include delete method
googleinterns/InterviewMe pull request #63
Opened 2020-07-08 19:56 UTC by GrantComm

As I was working on the datastore dao, I realized I needed to change the return type of my create method and add a delete method for the future cancellation feature.

2020-07-08 20:38 UTC, apluscs requested changes

2020-07-08 20:38 UTC, apluscs commented on src/main/java/com/google/sps/data/ScheduledInterviewDao.java
>    public void update(ScheduledInterview oldScheduledInterview);
This naming confuses me. Why is an `oldScheduledInterview` being put into datastore?

2020-07-08 20:38 UTC, apluscs commented on src/main/java/com/google/sps/data/ScheduledInterviewDao.java
> +  public void create(ScheduledInterview scheduledInterview);
Can you change create to put to match Datastore syntax?
Also less confusing for the Autovalue create()

2020-07-09 13:07 UTC, apluscs requested changes
One nit.

2020-07-09 13:07 UTC, apluscs commented on src/main/java/com/google/sps/data/ScheduledInterviewDao.java
> +  // Creates a ScheduledInterview entity and stores it in Datastore.
Since this is the interface, Datastore shouldn't be mentioned.

2020-07-09 19:31 UTC, apluscs approved these changes

2020-07-09 19:47 UTC, meagancheese approved these changes
LGTM

2020-07-09 21:32 UTC, jalexanderqed approved these changes

2020-07-09 21:33 UTC, merged