Added hardcoded Scheduled Interviews page
googleinterns/InterviewMe pull request #7
Opened 2020-06-23 19:53 UTC by apluscs

2020-06-23 21:19 UTC, meagancheese approved these changes
LGTM

2020-06-23 21:25 UTC, meagancheese commented
Attach screenshots as a comment or in the PR description. We can't see them in GitHub when it is just a file in the repo.

2020-06-23 21:31 UTC, jalexanderqed commented
@meagancheese It's possible to view the screenshot by clicking the "view rich diff" button on the right next to the file name.

2020-06-23 21:32 UTC, jalexanderqed requested changes

2020-06-23 21:32 UTC, jalexanderqed commented on src/main/webapp/scheduled-interviews.html
> +                <li class="list-group-item">Your role: Interviewer</li>
I think the user's role should be more prominent, probably at the top of the card with the same size as the date (<h5>). You may want to reformat it as "You are interviewing <first name of interviewee>" and "<first name of interviewer> is interviewing you," but the specifics of that are up to you. The main point is that it should be easy to tell at a glance what the user's role will be.

2020-06-24 14:56 UTC, meagancheese requested changes
Is there an easy way to make it so that the card is not much bigger than the text?

2020-06-24 15:31 UTC, meagancheese requested changes
Quick fix, instead of creating the scheduled-interviews-heading id you can apply the class "text-center"

2020-06-24 15:36 UTC, meagancheese approved these changes
LGTM

2020-06-24 16:35 UTC, jalexanderqed approved these changes

2020-06-24 17:43 UTC, merged