Added more dependencies for Datastore tests
googleinterns/InterviewMe pull request #84
Opened 2020-07-10 20:03 UTC by apluscs

Left these out the first time, oops

2020-07-10 20:07 UTC, GrantComm approved these changes
LGTM

2020-07-10 20:11 UTC, meagancheese requested changes

2020-07-10 20:11 UTC, meagancheese commented on pom.xml
> +    </dependency>
Indent by one space.

2020-07-10 20:46 UTC, meagancheese approved these changes
LGTM

2020-07-10 21:35 UTC, meagancheese approved these changes
LGTM

2020-07-10 21:36 UTC, GrantComm approved these changes
LGTM

2020-07-13 17:20 UTC, acmcarther commented
I'm LGTMing this, but how did the PR get submitted without these? The build should've been red.

2020-07-13 17:21 UTC, acmcarther approved these changes

2020-07-13 17:41 UTC, apluscs commented
l think Grant either pulled from this branch or added them in himself.

2020-07-13 17:41 UTC, merged